

all:
	gnuplot compress.plot
	gnuplot diff.plot
	gnuplot mpilatency.plot
	gnuplot pdhtlatency.plot
	gnuplot reconstruct.plot
	gnuplot scaling1k.plot
	gnuplot scaling64k.plot
	gnuplot meraculous.plot
